name: PR Label Manager - Advanced Example

on:
  pull_request:
    types: [opened, closed, converted_to_draft, ready_for_review, synchronize]
  pull_request_review:
    types: [submitted, dismissed]
  issue_comment:
    types: [created]
  push:
    branches: [main, develop, staging]
  schedule:
    - cron: '0 */6 * * *'

jobs:
  pr-manager:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      checks: read
    steps:
      - name: Manage PR Labels
        uses: your-username/pr-manager@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          stagingBranch: 'staging'
          productionBranch: 'main'
          abandonedTimeout: '14'
          checkConflicts: 'true'
          conflictCheckInterval: '30'
          teamId: 'Organization/Team-Name'
