name: PR Manager - Example Usage

on:
  pull_request:
    types: [opened, closed, converted_to_draft, ready_for_review, synchronize]
  pull_request_review:
    types: [submitted, dismissed]
  issue_comment:
    types: [created]
  push:
    branches: [main, staging]
  schedule:
    # Run every hour to check for abandoned PRs and merge conflicts
    - cron: '0 * * * *'

jobs:
  pr-manager:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      checks: read
    steps:
      - name: Manage PR Labels
        uses: filipemacedo/pr-manager@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          stagingBranch: 'staging'
          productionBranch: 'main'
          abandonedTimeout: '30'
          checkConflicts: 'true'
          conflictCheckInterval: '60'
          teamId: 'Organization/Team-Name'
